name: push docker to cloud and deploy
on:
  push:
    branches: [main]

env:
  IMAGE_NAME: nobelium
  DOCKER_HUB_NAMESPACE: ibule
  GITHUB_REGISTRY: ghcr.io
  TENCENT_DOCKER_REGISTRY: haomingkeji-docker.pkg.coding.net
  ALIYUN_DOCKER_REGISTRY: registry.cn-hongkong.aliyuncs.com
  ALIYUN_NAMESPACE: ibule
  TENCENT_NAMESPACE: public

jobs:
  push-dockerhub:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          push: true
          tags: |
            ibule/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}
            ibule/${{ env.IMAGE_NAME }}:latest
      - name: echo current tags
        run: |
          echo "发布dockerhub镜像 :rocket:" >> $GITHUB_STEP_SUMMARY
          echo ibule/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }} >> $GITHUB_STEP_SUMMARY

  push-GitHub:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{env.GITHUB_REGISTRY}}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{env.GITHUB_REGISTRY}}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{env.GITHUB_REGISTRY}}/${{ github.repository_owner}}/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}

  push-aliyun:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry.cn-hongkong.aliyuncs.com
        uses: docker/login-action@v2
        with:
          registry: ${{env.ALIYUN_DOCKER_REGISTRY}}
          username: mrhuxt@gmail.com
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{env.ALIYUN_DOCKER_REGISTRY}}/${{env.ALIYUN_NAMESPACE}}/${{ env.IMAGE_NAME }}:latest
            ${{env.ALIYUN_DOCKER_REGISTRY}}/${{ env.ALIYUN_NAMESPACE }}/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}

  push-tencent:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into registry haomingkeji-docker.pkg.coding.net
        uses: docker/login-action@v2
        with:
          registry: ${{env.TENCENT_DOCKER_REGISTRY}}
          username: ${{ secrets.TENCENT_CLOUD_USERNAME }}
          password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{env.TENCENT_DOCKER_REGISTRY}}/zaixiankaoshi/${{ env.TENCENT_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{env.TENCENT_DOCKER_REGISTRY}}/zaixiankaoshi/${{ env.TENCENT_NAMESPACE }}/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}

  deploy-tencent:
    runs-on: ubuntu-latest
    needs: [push-tencent]
    env:
      TZ: Asia/Shanghai
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ibule
          key: ${{ secrets.TENCENT_ID_RSA }}
          port: 22
          script: |
            cd ~ && echo "$(<deploy.sh)" > ~/deploy_by_github_action.sh && sh deploy_by_github_action.sh ${{ secrets.TENCENT_CLOUD_USERNAME}} ${{ secrets.TENCENT_CLOUD_PASSWORD }} #运行脚本
            # 检查脚本执行的返回码
            if [ $? -ne 0 ]; then
              echo "脚本执行失败！"
              exit 1
            fi
      - name: Get current date and time
        id: date
        run: echo "FORMATTED_TIME=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      - name: echo current tags
        run: |
          echo "### $FORMATTED_TIME 腾讯云部署成功 镜像号为： :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "### ${{env.TENCENT_DOCKER_REGISTRY}}/zaixiankaoshi/${{ env.TENCENT_NAMESPACE }}/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}"  >> $GITHUB_STEP_SUMMARY
