name: Docker ghcr.io
on:
  push:
    branches: [main]

env:
  IMAGE_NAME: nobelium
  DOCKER_HUB_NAMESPACE: ibule
  REGISTRY: ghcr.io
  TIME: $(date +'%Y-%m-%d-%H-%M')

jobs:
  get-current-date:
    runs-on: ubuntu-latest
    outputs:
      current_date: ${{ steps.date.outputs.current_date }}
    steps:
      - name: Get current date and time
        id: date
        run: echo "current_date=$(date +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"
      - name: Use date output
        run: echo ${{ steps.date.outputs.current_date }}
  push-dockerhub:
    runs-on: ubuntu-latest
    needs: get-current-date
    env:
      TZ: Asia/Shanghai
      CURRENT_DATE: ${{needs.get-current-date.outputs.current_date}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get current date and time
        run:  echo "current date: ${{CURRENT_DATE}}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          push: true
          tags: |
            ibule/${{ env.IMAGE_NAME }}:v1.0.${{ github.run_number }}
            ibule/${{ env.IMAGE_NAME }}:latest

  push-GitHub:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository}}:v1.0.${{ github.run_number }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.TENCENT_USERNAME }}
          password: ${{ secrets.TENCENT_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            docker ps
            docker compose ls
