name: Docker ghcr.io

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: nobelium
  DOCKER_HUB_NAMESPACE: ibule
  DOCKER_HUB_REGISTRY: nobelium

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log into registry ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get and Format Current Time
        id: formatted_time
        run: |
          echo "::set-output name=formatted_time::$(date +'%Y_%m_%d_%H_%M')"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NOTION_PAGE_ID=${{secrets.NOTION_PAGE_ID}}
          context: .
          tags: |
            ghcr.io/ibule/${{env.IMAGE_NAME}}:${{ steps.formatted_time.outputs.formatted_time }}
            ibule/${{env.IMAGE_NAME}}:${{ steps.formatted_time.outputs.formatted_time }}
            ibule/${{env.IMAGE_NAME}}:latest
